// AUTO-GENERATED by tools/sidecar-registry/generate.mjs — do not edit

export const SIDECAR_PORTS = {
  gin: 7101,
  express: 7102,
  fastapi: 7103,
  nest: 7104,
  axum: 7105,
} as const;

export type SidecarId = keyof typeof SIDECAR_PORTS;
