#!/usr/bin/env node
/**
 * Reads packages/contracts/ports.yaml and generates:
 *   - packages/api-client/src/constants.ts   (TypeScript port constants)
 *   - apps/desktop/src-tauri/src/sidecar/registry.rs  (Rust registry — OVERWRITES)
 *
 * Run with: pnpm generate  (from repo root)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "../..");

// ── parse ports.yaml ──────────────────────────────────────────────────────────

const yaml = readFileSync(resolve(root, "packages/contracts/ports.yaml"), "utf8");

function parsePortsYaml(text) {
  const services = [];
  let current = null;

  for (const raw of text.split("\n")) {
    const line = raw.trimEnd();
    const serviceMatch = line.match(/^  (\w+):$/);
    if (serviceMatch) {
      current = { key: serviceMatch[1] };
      services.push(current);
      continue;
    }
    if (!current) continue;

    const assign = (field, pattern) => {
      const m = line.match(pattern);
      if (m) current[field] = m[1];
    };
    assign("id", /^\s+id:\s+(.+)/);
    assign("port", /^\s+port:\s+(\d+)/);
    assign("healthPath", /^\s+healthPath:\s+(.+)/);
    assign("binaryName", /^\s+binaryName:\s+(.+)/);
  }
  return services.filter((s) => s.port);
}

const services = parsePortsYaml(yaml);

// ── emit TypeScript constants ─────────────────────────────────────────────────

const tsLines = [
  "// AUTO-GENERATED by tools/sidecar-registry/generate.mjs — do not edit",
  "",
  "export const SIDECAR_PORTS = {",
  ...services.map((s) => `  ${s.key}: ${s.port},`),
  "} as const;",
  "",
  "export type SidecarId = keyof typeof SIDECAR_PORTS;",
  "",
];

const tsOut = resolve(root, "packages/api-client/src/constants.ts");
writeFileSync(tsOut, tsLines.join("\n"));
console.log(`[generate] wrote ${tsOut}`);

// ── emit Rust registry ────────────────────────────────────────────────────────

const rustLines = [
  "// AUTO-GENERATED by tools/sidecar-registry/generate.mjs — do not edit",
  "",
  "pub struct SidecarEntry {",
  "    pub id: &'static str,",
  "    pub binary: &'static str,",
  "    pub port: u16,",
  "    pub health_path: &'static str,",
  "}",
  "",
  "pub const SIDECARS: &[SidecarEntry] = &[",
  ...services.map(
    (s) =>
      `    SidecarEntry { id: "${s.id}", binary: "${s.binaryName}", port: ${s.port}, health_path: "${s.healthPath}" },`
  ),
  "];",
  "",
];

const rustOut = resolve(
  root,
  "apps/desktop/src-tauri/src/sidecar/registry.rs"
);
writeFileSync(rustOut, rustLines.join("\n"));
console.log(`[generate] wrote ${rustOut}`);
